function PointsTable() {
  return (
    <table className="table table-striped table-sm">
      <thead>
        <tr className="hidden-sm-down">
          <th>Place</th>
          <th>Weeknights</th>
          <th>Majors</th>
          <th>Club Championship</th>
        </tr>
        <tr className="hidden-xs-up">
          <th></th>
          <th></th>
          <th>Majors</th>
          <th>CC</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1</td>
          <td>30</td>
          <td>60</td>
          <td>75</td>
        </tr>
        <tr>
          <td>2</td>
          <td>25</td>
          <td>50</td>
          <td>60</td>
        </tr>
        <tr>
          <td>3</td>
          <td>20</td>
          <td>40</td>
          <td>45</td>
        </tr>
        <tr>
          <td>4</td>
          <td>18</td>
          <td>36</td>
          <td>38</td>
        </tr>
        <tr>
          <td>5</td>
          <td>17</td>
          <td>34</td>
          <td>36</td>
        </tr>
        <tr>
          <td>6</td>
          <td>16</td>
          <td>32</td>
          <td>34</td>
        </tr>
        <tr>
          <td>7</td>
          <td>15</td>
          <td>30</td>
          <td>32</td>
        </tr>
        <tr>
          <td>8</td>
          <td>14</td>
          <td>28</td>
          <td>30</td>
        </tr>
        <tr>
          <td>9</td>
          <td>13</td>
          <td>26</td>
          <td>28</td>
        </tr>
        <tr>
          <td>10</td>
          <td>12</td>
          <td>24</td>
          <td>26</td>
        </tr>
        <tr>
          <td>11</td>
          <td>11</td>
          <td>22</td>
          <td>24</td>
        </tr>
        <tr>
          <td>12</td>
          <td>10</td>
          <td>20</td>
          <td>22</td>
        </tr>
        <tr>
          <td>13</td>
          <td>9</td>
          <td>18</td>
          <td>20</td>
        </tr>
        <tr>
          <td>14</td>
          <td>8</td>
          <td>16</td>
          <td>18</td>
        </tr>
        <tr>
          <td>15</td>
          <td>7</td>
          <td>14</td>
          <td>16</td>
        </tr>
        <tr>
          <td>16</td>
          <td>6</td>
          <td>12</td>
          <td>14</td>
        </tr>
        <tr>
          <td>17</td>
          <td>5</td>
          <td>10</td>
          <td>12</td>
        </tr>
        <tr>
          <td>18</td>
          <td>4</td>
          <td>8</td>
          <td>10</td>
        </tr>
        <tr>
          <td>19</td>
          <td>3</td>
          <td>6</td>
          <td>8</td>
        </tr>
        <tr>
          <td>20</td>
          <td>2</td>
          <td>4</td>
          <td>6</td>
        </tr>
        <tr>
          <td>others</td>
          <td>1</td>
          <td>2</td>
          <td>4</td>
        </tr>
      </tbody>
    </table>
  )
}

export default PointsTable
