import { TestingScreen } from "screens/testing"

var routes = [
  {
    path: "/home",
    layout: "admin",
    name: "Home",
    icon: "pe-7s-home",
    component: TestingScreen,
  },
  {
    path: "/calendar",
    layout: "admin",
    name: "Event Calendar",
    icon: "pe-7s-date",
    component: TestingScreen,
  },
  {
    path: "/match-play",
    layout: "admin",
    name: "Match Play",
    mini: "MP",
    component: TestingScreen,
  },
  {
    path: "/slp",
    layout: "admin",
    name: "Season Long Points",
    mini: "SLP",
    component: TestingScreen,
  },
  {
    path: "/dam-cup",
    layout: "admin",
    name: "Dam Cup",
    mini: "DC",
    component: TestingScreen,
  },
  {
    collapse: true,
    path: "/results",
    name: "Results",
    state: "openResults",
    icon: "pe-7s-note2",
    views: [
      {
        path: "/weeknights",
        layout: "admin",
        name: "Weeknights",
        mini: "W",
        component: TestingScreen,
      },
      {
        path: "/majors",
        layout: "admin",
        name: "Majors",
        mini: "M",
        component: TestingScreen,
      },
      {
        path: "/other",
        layout: "admin",
        name: "Other",
        mini: "O",
        component: TestingScreen,
      },
    ],
  },
  {
    collapse: true,
    path: "/policies",
    name: "Policies",
    state: "openPolicies",
    icon: "pe-7s-info",
    views: [
      {
        path: "/club",
        layout: "admin",
        name: "Club Procedures",
        mini: "CP",
        component: TestingScreen,
      },
      {
        path: "/rules",
        layout: "admin",
        name: "Local Rules",
        mini: "LR",
        component: TestingScreen,
      },
      {
        path: "/handicaps",
        layout: "admin",
        name: "Handicaps",
        mini: "H",
        component: TestingScreen,
      },
      {
        path: "/finances",
        layout: "admin",
        name: "Financial Info",
        mini: "$",
        component: TestingScreen,
      },
      {
        path: "/new-members",
        layout: "admin",
        name: "New Member Info",
        mini: "NM",
        component: TestingScreen,
      },
    ],
  },
  {
    path: "/directory",
    layout: "admin",
    name: "Member Directory",
    icon: "pe-7s-users",
    component: TestingScreen,
  },
  {
    path: "/contact-us",
    layout: "admin",
    name: "Contact Us",
    icon: "pe-7s-mail",
    component: TestingScreen,
  },
  {
    path: "/about-us",
    layout: "admin",
    name: "About Us",
    icon: "pe-7s-help1",
    component: TestingScreen,
  },
  {
    path: "/login",
    layout: "auth",
    name: "Login Page",
    icon: "pe-7s-key",
    component: TestingScreen,
  },
  {
    path: "/register",
    layout: "auth",
    name: "Register",
    icon: "pe-7s-add-user",
    component: TestingScreen,
  },
]

export default routes
